require: "standard"

inherit_gem:
  standard: "config/ruby-3.2.yml"

AllCops:
  SuggestExtensions: false

Style/FrozenStringLiteralComment:
  Enabled: true
  Include:
    - "app/**/*.rb"
  EnforcedStyle: "always_true"
